version: '2'

services:
  cli-8.1:
    build: docker/8.1
    restart: 'no'
    working_dir: /app
    volumes:
      - .:/app

  cli-8.2:
    build: docker/8.2
    restart: 'no'
    working_dir: /app
    volumes:
      - .:/app

  cli-8.3:
    build: docker/8.3
    restart: 'no'
    working_dir: /app
    volumes:
      - .:/app
